version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: ./compose/local/laravel/Dockerfile
    image: app
    env_file:
      - ./app/.env
    ports:
      - 9000:9000
    volumes:
      - ./app/:/var/www/app
    networks:
      - stock_notification

  redis:
    image: redis:6.0.9
    ports:
      - "6382:6379"
    networks:
      - stock_notification

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/app/
      - ./compose/local/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - stock_notification

  postgresql:
    image: postgres:12.4
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=stock_notification
      - POSTGRES_PASSWORD=sdjfHsd73
      - POSTGRES_DB=stock_notification_db
    networks:
      - stock_notification

volumes:
  postgres_data:
    driver: local

networks:
  stock_notification:
    driver: bridge